//----------------------------------------------------------------------------
//  This file is automatically generated, do not modify.      
//----------------------------------------------------------------------------



using System;
using System.Runtime.InteropServices;
using Emgu.CV;
using Emgu.CV.Structure;
using Emgu.Util;

namespace Emgu.CV.DepthAI
{
   public static partial class DepthAIInvoke
   {

     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern void cveHostDataPacketGetStreamName(IntPtr obj, IntPtr str);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveHostDataPacketSize(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern IntPtr cveHostDataPacketGetData(IntPtr obj);
     
     [DllImport(CvInvoke.ExternLibrary, CallingConvention = CvInvoke.CvCallingConvention)] 
     internal static extern int cveHostDataPacketGetElemSize(IntPtr obj);
     
   }

   public partial class HostDataPacket
   {

     /// <summary>
     /// Stream Name
     /// </summary>
     public String StreamName
     {
        get 
        { 
           using (CvString s = new CvString())
           {  
              DepthAIInvoke.cveHostDataPacketGetStreamName(_ptr, s); 
              return s.ToString();
           }
        }
     }
     
     /// <summary>
     /// Size
     /// </summary>
     public int Size
     {
        get { return DepthAIInvoke.cveHostDataPacketSize(_ptr); } 
     }
     
     /// <summary>
    /// Pointer to the native data
     /// </summary>
     public IntPtr Data
     {
        get { return DepthAIInvoke.cveHostDataPacketGetData(_ptr); } 
     }
     
     /// <summary>
     /// Element size
     /// </summary>
     public int ElemSize
     {
        get { return DepthAIInvoke.cveHostDataPacketGetElemSize(_ptr); } 
     }
     
   }
}
