// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file car.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace CarCounter.UWP
{
    
    public sealed class carInput
    {
        public TensorFloat modelInput; // shape(-1,3,448,640)
    }
    
    public sealed class carOutput
    {
        public TensorFloat modelOutput; // shape(-1,17640,10)
        public TensorFloat onnx00Sigmoid_527; // shape(-1,3,56,80,10)
        public TensorFloat onnx00Sigmoid_799; // shape(-1,3,28,40,10)
        public TensorFloat onnx00Sigmoid_1071; // shape(-1,3,14,20,10)
    }
    
    public sealed class carModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<carModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            carModel learningModel = new carModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<carOutput> EvaluateAsync(carInput input)
        {
            binding.Bind("modelInput", input.modelInput);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new carOutput();
            output.modelOutput = result.Outputs["modelOutput"] as TensorFloat;
            output.onnx00Sigmoid_527 = result.Outputs["onnx::Sigmoid_527"] as TensorFloat;
            output.onnx00Sigmoid_799 = result.Outputs["onnx::Sigmoid_799"] as TensorFloat;
            output.onnx00Sigmoid_1071 = result.Outputs["onnx::Sigmoid_1071"] as TensorFloat;
            return output;
        }
    }
}

